export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEMS="REMOVE_CART_ITEMS";
export const ADD_SHIPPING_INFO = "ADD_SHIPPING_INFO";
export const FAIL_SHIPPING_INFO = "FAIL_SHIPPING_INFO";
export const GET_SHIPPING_INFO = "GET_SHIPPING_INFO";