export const ADD_TO_CART = "ADD_TO_CART";
export const FAILED_CART = "FAILED_CART";
export const REMOVE_CART_ITEMS="REMOVE_CART_ITEMS";
export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";

