export const ADD_SHIPPING_INFO = "ADD_SHIPPING_INFO";
export const FAIL_SHIPPING_INFO = "FAIL_SHIPPING_INFO";
export const GET_SHIPPING_INFO = "GET_SHIPPING_INFO";
export const FAIL_GET_SHIPPING_INFO = "FAIL_GET_SHIPPING_INFO";
export const REQ_ADD_SHIPPINGINFO = "REQ_ADD_SHIPPINGINFO";
export const REQ_GET_SHIPPINGINFO = "REQ_GET_SHIPPINGINFO";
export const DELETE_SHIPPINGINFO = "DELETE_SHIPPINGINFO";




